#pragma once

#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS

#define MK_MOMENTARY_ACCEL
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_WHEEL_INTERVAL 40
#define MOUSEKEY_WHEEL_MAX_SPEED 16
